# Generated by Django 5.0.1 on 2024-01-15 03:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gameId', models.CharField(max_length=225)),
                ('answer', models.CharField(max_length=225)),
            ],
        ),
    ]
