# Generated by Django 5.0.1 on 2024-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0002_answermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
