# Generated by Django 5.0.1 on 2024-01-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0003_answermodel_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_backend.gamemodel'),
        ),
    ]
